#if you set the force configs any higher 8,
#you may not see much change to the knockback as it is about the limit
Knockback:
  radius: 3
  Fireball:
    Enabled: true
    radius-force: 3
    height-force: 1.5

#Set the fuse time of tnt
TNT-Fuse-Time: 5