#########################################
#FB-Knockback by MetallicGoat
#########################################

#Note: The damage config will effect both the thrower, and the target
#Whereas MBedwars's will only effect the target player

Knockback:
  enabled: true
  damage: 0
  radius: 3
  radius-force: 3
  height-force: 1.5