name: FireBallKnockback
version: 2.0
author: MetallicGoat
main: me.metallicgoat.FB.Knockback.Main
api-version: 1.13
description: FireBall Jumping for MBedwars
softdepend: [MBedwars]
commands:
  FB-knockback:
    usage: /<command>
    permission: FBknockback.admin